version: 0.2
phases:
   install:
      runtime-versions:
         docker: 18
   pre_build:
      commands:
      - echo "Entered the pre-build phase"
      - $(aws ecr get-login  --no-include-email --region $AWS_REGION)
   build:
      commands:
      - echo "Entered build phase"
      - cd authorization-service
      - mvn compile
      - mvn package
      - echo " building docker image"
      - docker build -t service/authapp .
      - docker tag service/authapp 137034369116.dkr.ecr.us-west-2.amazonaws.com/auth-registry:authapp
   post_build:
      commands:
      - echo "Entered the post-build phase"
      - docker push 137034369116.dkr.ecr.us-west-2.amazonaws.com/auth-registry:authapp
      - printf '[{"name":"authapp-container","imageUri":"%s"}]' 137034369116.dkr.ecr.us-west-2.amazonaws.com/auth-registry:authapp>taskdefinition.json
artifacts:
   files:
   - authorization-service/taskdefinition.json